const data: { code: string; name: string; currencyCode: string; }[] = [
    { code: 'ac', name: 'Ascension Island', currencyCode: '' },
    { code: 'ad', name: 'Andorra', currencyCode: '' },
    { code: 'ae', name: 'United Arab Emirates', currencyCode: 'AED' },
    // { code: 'af', name: 'Afghanistan', currencyCode: 'AFN' },
    { code: 'ag', name: 'Antigua and Barbuda', currencyCode: '' },
    { code: 'ai', name: 'Anguilla', currencyCode: '' },
    { code: 'al', name: 'Albania', currencyCode: 'ALL' },
    { code: 'am', name: 'Armenia', currencyCode: 'AMD' },
    { code: 'ao', name: 'Angola', currencyCode: 'AOA' },
    { code: 'aq', name: 'Antarctica', currencyCode: '' },
    { code: 'ar', name: 'Argentina', currencyCode: 'ARS' },
    { code: 'as', name: 'American Samoa', currencyCode: '' },
    { code: 'at', name: 'Austria', currencyCode: '' },
    { code: 'au', name: 'Australia', currencyCode: 'AUD' },
    { code: 'aw', name: 'Aruba', currencyCode: 'AWG' },
    { code: 'ax', name: 'Aland Islands', currencyCode: '' },
    { code: 'az', name: 'Azerbaijan', currencyCode: 'AZN' },
    { code: 'ba', name: 'Bosnia and Herzegovina', currencyCode: 'BAM' },
    { code: 'bb', name: 'Barbados', currencyCode: 'BBD' },
    { code: 'bd', name: 'Bangladesh', currencyCode: 'BDT' },
    { code: 'be', name: 'Belgium', currencyCode: '' },
    { code: 'bf', name: 'Burkina Faso', currencyCode: '' },
    { code: 'bg', name: 'Bulgaria', currencyCode: 'BGN' },
    { code: 'bh', name: 'Bahrain', currencyCode: 'BHD' },
    { code: 'bi', name: 'Burundi', currencyCode: 'BIF' },
    { code: 'bj', name: 'Benin', currencyCode: '' },
    { code: 'bl', name: 'Saint Barth\u00e9lemy', currencyCode: '' },
    { code: 'bm', name: 'Bermuda', currencyCode: 'BMD' },
    { code: 'bn', name: 'Brunei Darussalam', currencyCode: 'BND' },
    { code: 'bo', name: 'Bolivia (Plurinational State of)', currencyCode: 'BOB' },
    { code: 'bq', name: 'Bonaire, Sint Eustatius and Saba', currencyCode: '' },
    { code: 'br', name: 'Brazil', currencyCode: 'BRL' },
    { code: 'bs', name: 'Bahamas', currencyCode: 'BSD' },
    { code: 'bt', name: 'Bhutan', currencyCode: 'BTN' },
    { code: 'bv', name: 'Bouvet Island', currencyCode: 'NOK' },
    { code: 'bw', name: 'Botswana', currencyCode: 'BWP' },
    { code: 'by', name: 'Belarus', currencyCode: 'BYR' },
    { code: 'bz', name: 'Belize', currencyCode: 'BZD' },
    { code: 'ca', name: 'Canada', currencyCode: 'CAD' },
    { code: 'cc', name: 'Cocos (Keeling) Islands', currencyCode: '' },
    { code: 'cd', name: 'Democratic Republic of the Congo', currencyCode: 'CDF' },
    { code: 'cefta', name: 'Central European Free Trade Agreement', currencyCode: '' },
    { code: 'cf', name: 'Central African Republic', currencyCode: '' },
    { code: 'cg', name: 'Republic of the Congo', currencyCode: 'CDF' },
    { code: 'ch', name: 'Switzerland', currencyCode: 'CHF' },
    { code: 'ci', name: 'C\u00f4te d\'Ivoire', currencyCode: '' },
    { code: 'ck', name: 'Cook Islands', currencyCode: '' },
    { code: 'cl', name: 'Chile', currencyCode: 'CLP' },
    { code: 'cm', name: 'Cameroon', currencyCode: '' },
    { code: 'cn', name: 'China', currencyCode: 'CNY' },
    { code: 'co', name: 'Colombia', currencyCode: 'COP' },
    { code: 'cp', name: 'Clipperton Island', currencyCode: '' },
    { code: 'cr', name: 'Costa Rica', currencyCode: 'CRC' },
    { code: 'cu', name: 'Cuba', currencyCode: 'CUP' },
    { code: 'cv', name: 'Cabo Verde', currencyCode: 'CVE' },
    { code: 'cw', name: 'Cura\u00e7ao', currencyCode: '' },
    { code: 'cx', name: 'Christmas Island', currencyCode: '' },
    { code: 'cy', name: 'Cyprus', currencyCode: '' },
    { code: 'cz', name: 'Czech Republic', currencyCode: 'CZK' },
    { code: 'de', name: 'Germany', currencyCode: '' },
    { code: 'dg', name: 'Diego Garcia', currencyCode: '' },
    { code: 'dj', name: 'Djibouti', currencyCode: 'DJF' },
    { code: 'dk', name: 'Denmark', currencyCode: 'DKK' },
    { code: 'dm', name: 'Dominica', currencyCode: '' },
    { code: 'do', name: 'Dominican Republic', currencyCode: 'DOP' },
    { code: 'dz', name: 'Algeria', currencyCode: 'DZD' },
    { code: 'ea', name: 'Ceuta & Melilla', currencyCode: '' },
    { code: 'ec', name: 'Ecuador', currencyCode: '' },
    { code: 'ee', name: 'Estonia', currencyCode: '' },
    { code: 'eg', name: 'Egypt', currencyCode: 'EGP' },
    { code: 'eh', name: 'Western Sahara', currencyCode: 'MAD' },
    { code: 'er', name: 'Eritrea', currencyCode: 'ERN' },
    { code: 'es', name: 'Spain', currencyCode: '' },
    { code: 'es-ct', name: 'Catalonia', currencyCode: '' },
    { code: 'es-ga', name: 'Galicia', currencyCode: '' },
    { code: 'et', name: 'Ethiopia', currencyCode: 'ETB' },
    { code: 'eu', name: 'Europe', currencyCode: 'EUR' },
    { code: 'fi', name: 'Finland', currencyCode: '' },
    { code: 'fj', name: 'Fiji', currencyCode: 'FJD' },
    { code: 'fk', name: 'Falkland Islands', currencyCode: 'FKP' },
    { code: 'fm', name: 'Federated States of Micronesia', currencyCode: '' },
    { code: 'fo', name: 'Faroe Islands', currencyCode: '' },
    { code: 'fr', name: 'France', currencyCode: '' },
    { code: 'ga', name: 'Gabon', currencyCode: '' },
    { code: 'gb', name: 'United Kingdom', currencyCode: 'GBP' },
    { code: 'gb-eng', name: 'England', currencyCode: '' },
    { code: 'gb-nir', name: 'Northern Ireland', currencyCode: '' },
    { code: 'gb-sct', name: 'Scotland', currencyCode: '' },
    { code: 'gb-wls', name: 'Wales', currencyCode: '' },
    { code: 'gd', name: 'Grenada', currencyCode: '' },
    { code: 'ge', name: 'Georgia', currencyCode: 'GEL' },
    { code: 'gf', name: 'French Guiana', currencyCode: '' },
    { code: 'gg', name: 'Guernsey', currencyCode: 'GGP' },
    { code: 'gh', name: 'Ghana', currencyCode: 'GHS' },
    { code: 'gi', name: 'Gibraltar', currencyCode: 'GIP' },
    { code: 'gl', name: 'Greenland', currencyCode: 'DKK' },
    { code: 'gm', name: 'Gambia', currencyCode: 'GMD' },
    { code: 'gn', name: 'Guinea', currencyCode: 'GNF' },
    { code: 'gp', name: 'Guadeloupe', currencyCode: '' },
    { code: 'gq', name: 'Equatorial Guinea', currencyCode: '' },
    { code: 'gr', name: 'Greece', currencyCode: '' },
    { code: 'gs', name: 'South Georgia and the South Sandwich Islands', currencyCode: '' },
    { code: 'gt', name: 'Guatemala', currencyCode: 'GTQ' },
    { code: 'gu', name: 'Guam', currencyCode: '' },
    { code: 'gw', name: 'Guinea-Bissau', currencyCode: '' },
    { code: 'gy', name: 'Guyana', currencyCode: 'GYD' },
    { code: 'hk', name: 'Hong Kong', currencyCode: 'HKD' },
    { code: 'hm', name: 'Heard Island and McDonald Islands', currencyCode: '' },
    { code: 'hn', name: 'Honduras', currencyCode: 'HNL' },
    { code: 'hr', name: 'Croatia', currencyCode: '' },
    { code: 'ht', name: 'Haiti', currencyCode: 'HTG' },
    { code: 'hu', name: 'Hungary', currencyCode: 'HUF' },
    { code: 'ic', name: 'Canary Islands', currencyCode: '' },
    { code: 'id', name: 'Indonesia', currencyCode: 'IDR' },
    { code: 'ie', name: 'Ireland', currencyCode: '' },
    { code: 'il', name: 'Israel', currencyCode: 'ILS' },
    { code: 'im', name: 'Isle of Man', currencyCode: 'IMP' },
    { code: 'in', name: 'India', currencyCode: 'INR' },
    { code: 'io', name: 'British Indian Ocean Territory', currencyCode: '' },
    { code: 'iq', name: 'Iraq', currencyCode: 'IQD' },
    { code: 'ir', name: 'Iran (Islamic Republic of)', currencyCode: 'IRR' },
    { code: 'is', name: 'Iceland', currencyCode: 'ISK' },
    { code: 'it', name: 'Italy', currencyCode: '' },
    { code: 'je', name: 'Jersey', currencyCode: 'JEP' },
    { code: 'jm', name: 'Jamaica', currencyCode: 'JMD' },
    { code: 'jo', name: 'Jordan', currencyCode: 'JOD' },
    { code: 'jp', name: 'Japan', currencyCode: 'JPY' },
    { code: 'ke', name: 'Kenya', currencyCode: 'KES' },
    { code: 'kg', name: 'Kyrgyzstan', currencyCode: 'KGS' },
    { code: 'kh', name: 'Cambodia', currencyCode: 'KHR' },
    { code: 'ki', name: 'Kiribati', currencyCode: '' },
    { code: 'km', name: 'Comoros', currencyCode: 'KMF' },
    { code: 'kn', name: 'Saint Kitts and Nevis', currencyCode: '' },
    { code: 'kp', name: 'North Korea', currencyCode: 'KPW' },
    { code: 'kr', name: 'South Korea', currencyCode: 'KRW' },
    { code: 'kw', name: 'Kuwait', currencyCode: 'KWD' },
    { code: 'ky', name: 'Cayman Islands', currencyCode: 'KYD' },
    { code: 'kz', name: 'Kazakhstan', currencyCode: 'KZT' },
    { code: 'la', name: 'Laos', currencyCode: 'LAK' },
    { code: 'lb', name: 'Lebanon', currencyCode: 'LBP' },
    { code: 'lc', name: 'Saint Lucia', currencyCode: '' },
    { code: 'li', name: 'Liechtenstein', currencyCode: 'CHF' },
    { code: 'lk', name: 'Sri Lanka', currencyCode: 'LKR' },
    { code: 'lr', name: 'Liberia', currencyCode: 'LRD' },
    { code: 'ls', name: 'Lesotho', currencyCode: 'LSL' },
    { code: 'lt', name: 'Lithuania', currencyCode: '' },
    { code: 'lu', name: 'Luxembourg', currencyCode: '' },
    { code: 'lv', name: 'Latvia', currencyCode: '' },
    { code: 'ly', name: 'Libya', currencyCode: 'LYD' },
    { code: 'ma', name: 'Morocco', currencyCode: 'MAD' },
    { code: 'mc', name: 'Monaco', currencyCode: '' },
    { code: 'md', name: 'Moldova', currencyCode: 'MDL' },
    { code: 'me', name: 'Montenegro', currencyCode: '' },
    { code: 'mf', name: 'Saint Martin', currencyCode: '' },
    { code: 'mg', name: 'Madagascar', currencyCode: 'MGA' },
    { code: 'mh', name: 'Marshall Islands', currencyCode: '' },
    { code: 'mk', name: 'North Macedonia', currencyCode: 'MKD' },
    { code: 'ml', name: 'Mali', currencyCode: '' },
    { code: 'mm', name: 'Myanmar', currencyCode: '' },
    { code: 'mn', name: 'Mongolia', currencyCode: 'MNT' },
    { code: 'mo', name: 'Macau', currencyCode: 'MOP' },
    { code: 'mp', name: 'Northern Mariana Islands', currencyCode: '' },
    { code: 'mq', name: 'Martinique', currencyCode: '' },
    { code: 'mr', name: 'Mauritania', currencyCode: 'MRO' },
    { code: 'ms', name: 'Montserrat', currencyCode: '' },
    { code: 'mt', name: 'Malta', currencyCode: '' },
    { code: 'mu', name: 'Mauritius', currencyCode: 'MUR' },
    { code: 'mv', name: 'Maldives', currencyCode: 'MVR' },
    { code: 'mw', name: 'Malawi', currencyCode: 'MWK' },
    { code: 'mx', name: 'Mexico', currencyCode: 'MXN' },
    { code: 'my', name: 'Malaysia', currencyCode: 'MYR' },
    { code: 'mz', name: 'Mozambique', currencyCode: 'MZN' },
    { code: 'na', name: 'Namibia', currencyCode: 'NAD' },
    { code: 'nc', name: 'New Caledonia', currencyCode: '' },
    { code: 'ne', name: 'Niger', currencyCode: '' },
    { code: 'nf', name: 'Norfolk Island', currencyCode: '' },
    { code: 'ng', name: 'Nigeria', currencyCode: 'NGN' },
    { code: 'ni', name: 'Nicaragua', currencyCode: 'NIO' },
    { code: 'nl', name: 'Netherlands', currencyCode: '' },
    { code: 'no', name: 'Norway', currencyCode: 'NOK' },
    { code: 'np', name: 'Nepal', currencyCode: 'NPR' },
    { code: 'nr', name: 'Nauru', currencyCode: '' },
    { code: 'nu', name: 'Niue', currencyCode: 'NZD' },
    { code: 'nz', name: 'New Zealand', currencyCode: 'NZD' },
    { code: 'om', name: 'Oman', currencyCode: 'OMR' },
    { code: 'pa', name: 'Panama', currencyCode: 'PAB' },
    { code: 'pe', name: 'Peru', currencyCode: 'PEN' },
    { code: 'pf', name: 'French Polynesia', currencyCode: '' },
    { code: 'pg', name: 'Papua New Guinea', currencyCode: 'PGK' },
    { code: 'ph', name: 'Philippines', currencyCode: 'PHP' },
    { code: 'pk', name: 'Pakistan', currencyCode: 'PKR' },
    { code: 'pl', name: 'Poland', currencyCode: 'PLN' },
    { code: 'pm', name: 'Saint Pierre and Miquelon', currencyCode: '' },
    { code: 'pn', name: 'Pitcairn', currencyCode: 'NZD' },
    { code: 'pr', name: 'Puerto Rico', currencyCode: '' },
    { code: 'ps', name: 'State of Palestine', currencyCode: 'ILS' },
    { code: 'pt', name: 'Portugal', currencyCode: '' },
    { code: 'pw', name: 'Palau', currencyCode: '' },
    { code: 'py', name: 'Paraguay', currencyCode: 'PYG' },
    { code: 'qa', name: 'Qatar', currencyCode: 'QAR' },
    { code: 're', name: 'R\u00e9union', currencyCode: '' },
    { code: 'ro', name: 'Romania', currencyCode: 'RON' },
    { code: 'rs', name: 'Serbia', currencyCode: 'RSD' },
    { code: 'ru', name: 'Russia', currencyCode: 'RUB' },
    { code: 'rw', name: 'Rwanda', currencyCode: 'RWF' },
    { code: 'sa', name: 'Saudi Arabia', currencyCode: 'SAR' },
    { code: 'sb', name: 'Solomon Islands', currencyCode: 'SBD' },
    { code: 'sc', name: 'Seychelles', currencyCode: 'SCR' },
    { code: 'sd', name: 'Sudan', currencyCode: 'SDG' },
    { code: 'se', name: 'Sweden', currencyCode: 'SEK' },
    { code: 'sg', name: 'Singapore', currencyCode: 'SGD' },
    { code: 'sh', name: 'Saint Helena, Ascension and Tristan da Cunha', currencyCode: 'SHP' },
    { code: 'si', name: 'Slovenia', currencyCode: '' },
    { code: 'sj', name: 'Svalbard and Jan Mayen', currencyCode: 'NOK' }, // Точно?
    { code: 'sk', name: 'Slovakia', currencyCode: '' },
    { code: 'sl', name: 'Sierra Leone', currencyCode: 'SLL' },
    { code: 'sm', name: 'San Marino', currencyCode: '' },
    { code: 'sn', name: 'Senegal', currencyCode: '' },
    { code: 'so', name: 'Somalia', currencyCode: 'SOS' },
    { code: 'sr', name: 'Suriname', currencyCode: 'SRD' },
    { code: 'ss', name: 'South Sudan', currencyCode: '' },
    { code: 'st', name: 'Sao Tome and Principe', currencyCode: 'STD' },
    { code: 'sv', name: 'El Salvador', currencyCode: '' },
    { code: 'sx', name: 'Sint Maarten', currencyCode: 'ANG' },
    { code: 'sy', name: 'Syrian Arab Republic', currencyCode: 'SYP' },
    { code: 'sz', name: 'Swaziland', currencyCode: '' },
    { code: 'ta', name: 'Tristan da Cunha', currencyCode: '' },
    { code: 'tc', name: 'Turks and Caicos Islands', currencyCode: '' },
    { code: 'td', name: 'Chad', currencyCode: '' },
    { code: 'tf', name: 'French Southern Territories', currencyCode: '' },
    { code: 'tg', name: 'Togo', currencyCode: '' },
    { code: 'th', name: 'Thailand', currencyCode: 'THB' },
    { code: 'tj', name: 'Tajikistan', currencyCode: 'TJS' },
    { code: 'tk', name: 'Tokelau', currencyCode: 'NZD' },
    { code: 'tl', name: 'Timor-Leste', currencyCode: '' },
    { code: 'tm', name: 'Turkmenistan', currencyCode: 'TMT' },
    { code: 'tn', name: 'Tunisia', currencyCode: 'TND' },
    { code: 'to', name: 'Tonga', currencyCode: 'TOP' },
    { code: 'tr', name: 'Turkey', currencyCode: 'TRY' },
    { code: 'tt', name: 'Trinidad and Tobago', currencyCode: 'TTD' },
    { code: 'tv', name: 'Tuvalu', currencyCode: '' },
    { code: 'tw', name: 'Taiwan', currencyCode: 'TWD' },
    { code: 'tz', name: 'Tanzania', currencyCode: 'TZS' },
    { code: 'ua', name: 'Ukraine', currencyCode: 'UAH' },
    { code: 'ug', name: 'Uganda', currencyCode: 'UGX' },
    { code: 'um', name: 'United States Minor Outlying Islands', currencyCode: '' },
    { code: 'un', name: 'United Nations', currencyCode: '' },
    { code: 'us', name: 'United States of America', currencyCode: 'USD' },
    { code: 'uy', name: 'Uruguay', currencyCode: 'UYU' },
    { code: 'uz', name: 'Uzbekistan', currencyCode: 'UZS' },
    { code: 'va', name: 'Holy See', currencyCode: '' },
    { code: 'vc', name: 'Saint Vincent and the Grenadines', currencyCode: '' },
    { code: 've', name: 'Venezuela (Bolivarian Republic of)', currencyCode: 'VEF' },
    { code: 'vg', name: 'Virgin Islands (British)', currencyCode: '' },
    { code: 'vi', name: 'Virgin Islands (U.S.)', currencyCode: '' },
    { code: 'vn', name: 'Vietnam', currencyCode: 'VND' },
    { code: 'vu', name: 'Vanuatu', currencyCode: 'VUV' },
    { code: 'wf', name: 'Wallis and Futuna', currencyCode: '' },
    { code: 'ws', name: 'Samoa', currencyCode: 'WST' },
    { code: 'xk', name: 'Kosovo', currencyCode: '' },
    { code: 'xx', name: 'Unknown', currencyCode: '' },
    { code: 'ye', name: 'Yemen', currencyCode: 'YER' },
    { code: 'yt', name: 'Mayotte', currencyCode: '' },
    { code: 'za', name: 'South Africa', currencyCode: 'ZAR' },
    { code: 'zm', name: 'Zambia', currencyCode: 'ZMW' },
    { code: 'zw', name: 'Zimbabwe', currencyCode: 'ZWL' },
    { code: '_none_country__btc', name: 'BITCOIN', currencyCode: 'BTC' },
].filter((x) => x.currencyCode !== '');

// BTC ?!))
// BYN ?!))
// CLF ?!))
// CUC
// HRK
// LTL
// LVL
// MMK
// SVC
// SZL
// XAG

// const flagsMap = {
//     XAF: '', // Gabon, Cameroon, Central African Republic, Equatorial Guinea, Chad
//     // XAU: '',
//     XCD: '', // Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines
//     // XDR: '',
//     XOF: '', // Benin, Burkina Faso, Guinea-Bissau, Mali, Niger, Ivory Coast, Senegal, Togo
//     XPF: '', // French Polynesia, New Caledonia, Wallis and Futuna
//     // ZMK: '',
// };

export const countries = data;

export const currencyMap = data.reduce((acc, item) => {
    acc[item.currencyCode] = item.code;

    return acc;
}, {} as Record<string, string>);
