name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v16.16.0

      - name: Install dependencies
        run: npm ci

      - name: Start build
        run: npm run build
