name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v16.16.0

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Install AWS cli
        uses: unfor19/install-aws-cli-action@master

      - name: Start build
        run: npm run build

      - name: Start deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: npm run deploy
